### ISSUE TITLE
Не стоит заглушать ошибки

### ISSUE THREAD

**Issue by los-romka** [ykropchik/todo_service#3]
https://github.com/ykropchik/todo_service/blob/5a122912309d0f53e765dab09827087cec57f98a/src/Service/FileUploader.php#L28

Хорошая политика - это выбросить "своё" исключение, но не возвращать тот же тип. В вашем случае сервер в итоге не сможет отличить ошибку от нормальной работы приложения.

**Comment by ykropchik** [comment]
> Хорошая политика - это выбросить "своё" исключение, но не возвращать тот же тип. В вашем случае сервер в итоге не сможет отличить ошибку от нормальной работы приложения.

То есть я должен сделать как-то так?
```php
try {
    $file->move($this->targetDirectory, $fileName);
} catch (FileException $e) {
    throw new ErrorException(...);
}
```
